/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LastUpdated {
	basic: string | null;
	easy: string | null;
	hard: string | null;
	wild: string | null;
	dual: string | null;
	full: string | null;
}
