/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PlayerStats = {
	id: number;
	username: string;
	picture_path: string;
	rank?: number;
	rank_region?: number;
	weekly_rank?: number;
	rank_beginner?: number;
	rank_easy?: number;
	rank_hard?: number;
	rank_wild?: number;
	rank_dual?: number;
	rank_full?: number;
	rank_region_beginner?: number;
	rank_region_easy?: number;
	rank_region_hard?: number;
	rank_region_wild?: number;
	rank_region_dual?: number;
	rank_region_full?: number;
} & ({
	id: number;
	username: string;
	picture_path: string;
	rank?: number;
	rank_region?: number;
	weekly_rank?: number;
	rank_beginner?: number;
	rank_easy?: number;
	rank_hard?: number;
	rank_wild?: number;
	rank_dual?: number;
	rank_full?: number;
	rank_region_beginner?: number;
	rank_region_easy?: number;
	rank_region_hard?: number;
	rank_region_wild?: number;
	rank_region_dual?: number;
	rank_region_full?: number;
} | null);
