/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MaybeModeSummary = ModeSummary | null;

export interface ScoreSummary {
	basic: MaybeModeSummary;
	easy: MaybeModeSummary;
	hard: MaybeModeSummary;
	wild: MaybeModeSummary;
	dual: MaybeModeSummary;
	full: MaybeModeSummary;
}
export interface ModeSummary {
	inTotal: Summary;
	byLevel: {
		[k: string]: Summary;
	};
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "$[0-9]+$".
 */
export interface Summary {
	passes: number;
	fullCombos: number;
	threeStar: number;
	fourStar: number;
	fiveStar: number;
	sixStar: number;
	apcs: number;
}
